INCLUDES = -I../../../../include -I${master_top_srcdir}/src/include
lib${MPILIBNAME}_a_SOURCES =   \
 ch3u_get_business_card_sshm.c \
 ch3u_init_sshm.c              \
 ch3u_finalize_sshm.c          \
 ch3i_bootstrapq.c             \
 ch3i_shm_bootstrapq.c         \
 ch3u_connect_sshm.c           \
 shmproc.c
