F77INCLUDES = -I.
LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

statusesf_SOURCES = statusesf.f
greqf_SOURCES     = greqf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
