#!/bin/csh -f

set nonomatch


foreach dir ( frame chem share dyn_em dyn_exp dyn_nmm phys main tools )
( cd $dir ; echo $dir ; /bin/rm -f core wrf *.f *.exe *.kmo *.mod *.o *.inc *.F90 *.a .*.m *.lst \
                      db_* Warnings module_state_description.F module_dm.F gmeta \
                      wrfdata whatiread rsl.* show_domain* )
end

( cd da_3dvar ; /bin/rm -f *.f *.o *.mod mpif.h *.stb .*.m *.lst )
( cd da_3dvar/src ; /bin/rm -f *.f *.o *.mod *.stb .*.m *.lst )
( cd external/RSL/RSL ; /bin/rm -f *.lst )
( cd convertor ; /bin/rm -f *.f *.o *.mod *.exe *.stb .*.m *.lst )
( cd gen_be ; /bin/rm -f *.o *.mod *.exe *.stb .*.m *.lst )

( cd tools/CodeBase ; make clean )

( cd inc ; /bin/rm -f *.inc namelist.default )


if ( "$1" == '-a' ) then
  if ( -f configure.wrf ) then
    /bin/cp configure.wrf configure.wrf.backup
    /bin/rm -f configure.wrf
  endif

  if ( -f configure.3dvar ) then
    /bin/cp configure.3dvar configure.3dvar.backup
    /bin/rm -f configure.3dvar
  endif

  if ( -f Registry/Registry ) then
    /bin/cp Registry/Registry Registry/Registry.backup
    /bin/rm -f Registry/Registry
  endif

  /bin/rm -fr ./netcdf_links
  /bin/rm -fr tools/code_dbase
  ( cd external ; make -i superclean )
  ( cd tools ; /bin/rm -f registry gen_comms.c )
  ( cd inc; /bin/rm -f dm_comm_cpp_flags wrf_io_flags.h wrf_status_codes.h )
  ( cd run ; /bin/rm -f gm* out* fort* ideal* )
  ( cd test/exp_real ; /bin/rm -f gm* out* fort* real* )

  ( /bin/rm -f main/mpif.h main/*.stb )
  ( /bin/rm -f da_3dvar/src/mpif.h )
  ( /bin/rm -f external/io_netcdf/mpif.h )
  ( /bin/rm -fr ./netcdf_links )
  ( /bin/rm -f core *.out 1 )
endif

