#!/bin/csh -f

cd build

cat > configure.wrfvar <<EOF
RM=rm -rf
arch_superclean:
arch_clean:
EOF

touch depend.txt

if ( "$1" == '-a' ) then
  make superclean
else
  make clean
endif

rm -f ../main/*exe

