.TH MPI_File_set_size 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_set_size \-  Sets the file size 
.SH SYNOPSIS
.nf
int MPI_File_set_size(MPI_File mpi_fh, MPI_Offset size)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1
.PD 0
.TP
.B size 
- size to truncate or expand file (nonnegative integer)
.PD 1

.SH LOCATION
set_size.c
