.TH MPI_File_set_info 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_set_info \-  Sets new values for the hints associated with a file 
.SH SYNOPSIS
.nf
int MPI_File_set_info(MPI_File mpi_fh, MPI_Info info)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1
.PD 0
.TP
.B info 
- info object (handle)
.PD 1

.SH LOCATION
set_info.c
