subroutine DA_Deallocate_Constants

!------------------------------------------------------------------------------
!  PURPOSE: Deallocate constant arrays defined in DA_Constants.
!
!  METHOD:  Straightforward.
!
!  HISTORY: 08/25/00    - Original f90 version. Dale Barker
!-----------------------------------------------------------------------------

   IMPLICIT NONE

!------------------------------------------------------------------------------
!  [1.0] Recursive filter:
!------------------------------------------------------------------------------

!   DEALLOCATE( rf_turnconds )

end subroutine DA_Deallocate_Constants
