mpi_sources = abort.c init.c initialized.c initthread.c \
 ismain.c finalize.c finalized.c querythread.c
HEADERS = mpi_init.h
lib${MPILIBNAME}_a_SOURCES = ${mpi_sources}
profilelib_${MPILIBNAME} = ${PMPILIBNAME}
INCLUDES = -I../../include -I${top_srcdir}/src/include -I${top_srcdir}/src/mpi/datatype -I${master_top_srcdir}/src/mpi/spawn
#
doc_HTML_SOURCES = ${mpi_sources}
doc_MAN_SOURCES = ${mpi_sources}
doc_LATEX_SOURCES = ${mpi_sources}
