.TH MPI_File_delete 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_delete \-  Deletes a file 
.SH SYNOPSIS
.nf
int MPI_File_delete(char *filename, MPI_Info info)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B filename 
- name of file to delete (string)
.PD 1
.PD 0
.TP
.B info 
- info object (handle)
.PD 1

.SH LOCATION
delete.c
