.TH MPI_File_seek_shared 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_seek_shared \-  Updates the shared file pointer 
.SH SYNOPSIS
.nf
int MPI_File_seek_shared(MPI_File mpi_fh, MPI_Offset offset, int whence)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1
.PD 0
.TP
.B offset 
- file offset (integer)
.PD 1
.PD 0
.TP
.B whence 
- update mode (state)
.PD 1

.SH LOCATION
seek_sh.c
