.TH MPI_File_open 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_open \-  Opens a file 
.SH SYNOPSIS
.nf
int MPI_File_open(MPI_Comm comm, char *filename, int amode, 
                  MPI_Info info, MPI_File *fh)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator (handle)
.PD 1
.PD 0
.TP
.B filename 
- name of file to open (string)
.PD 1
.PD 0
.TP
.B amode 
- file access mode (integer)
.PD 1
.PD 0
.TP
.B info 
- info object (handle)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1

.SH LOCATION
open.c
