.TH MPI_File_preallocate 3 "1/30/2007" " " "MPI"
.SH NAME
MPI_File_preallocate \-  Preallocates storage space for a file 
.SH SYNOPSIS
.nf
int MPI_File_preallocate(MPI_File mpi_fh, MPI_Offset size)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1
.PD 0
.TP
.B size 
- size to preallocate (nonnegative integer)
.PD 1

.SH LOCATION
prealloc.c
