LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

commnamef_SOURCES = commnamef.f
commerrf_SOURCES = commerrf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
