/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK) && defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_GREQUEST_COMPLETE( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete_( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL pmpi_grequest_complete_( MPI_Fint *, MPI_Fint * );

#pragma weak MPI_GREQUEST_COMPLETE = pmpi_grequest_complete__
#pragma weak mpi_grequest_complete__ = pmpi_grequest_complete__
#pragma weak mpi_grequest_complete_ = pmpi_grequest_complete__
#pragma weak mpi_grequest_complete = pmpi_grequest_complete__
#pragma weak pmpi_grequest_complete_ = pmpi_grequest_complete__


#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GREQUEST_COMPLETE( MPI_Fint *, MPI_Fint * );

#pragma weak MPI_GREQUEST_COMPLETE = PMPI_GREQUEST_COMPLETE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete__( MPI_Fint *, MPI_Fint * );

#pragma weak mpi_grequest_complete__ = pmpi_grequest_complete__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete( MPI_Fint *, MPI_Fint * );

#pragma weak mpi_grequest_complete = pmpi_grequest_complete
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete_( MPI_Fint *, MPI_Fint * );

#pragma weak mpi_grequest_complete_ = pmpi_grequest_complete_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_GREQUEST_COMPLETE  MPI_GREQUEST_COMPLETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_grequest_complete__  mpi_grequest_complete__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_grequest_complete  mpi_grequest_complete
#else
#pragma _HP_SECONDARY_DEF pmpi_grequest_complete_  mpi_grequest_complete_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_GREQUEST_COMPLETE as PMPI_GREQUEST_COMPLETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_grequest_complete__ as pmpi_grequest_complete__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_grequest_complete as pmpi_grequest_complete
#else
#pragma _CRI duplicate mpi_grequest_complete_ as pmpi_grequest_complete_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYBMOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPI_GREQUEST_COMPLETE( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete_( MPI_Fint *, MPI_Fint * );

#pragma weak MPI_GREQUEST_COMPLETE = mpi_grequest_complete__
#pragma weak mpi_grequest_complete_ = mpi_grequest_complete__
#pragma weak mpi_grequest_complete = mpi_grequest_complete__
#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#ifdef F77_NAME_UPPER
#define mpi_grequest_complete_ PMPI_GREQUEST_COMPLETE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_grequest_complete_ pmpi_grequest_complete__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_grequest_complete_ pmpi_grequest_complete
#else
#define mpi_grequest_complete_ pmpi_grequest_complete_
#endif
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings,
   such as those put in place by the globus device when it is building on
   top of a vendor MPI. */
#undef MPI_Grequest_complete
#define MPI_Grequest_complete PMPI_Grequest_complete 

#else

#ifdef F77_NAME_UPPER
#define mpi_grequest_complete_ MPI_GREQUEST_COMPLETE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_grequest_complete_ mpi_grequest_complete__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_grequest_complete_ mpi_grequest_complete
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_grequest_complete_ ( MPI_Fint *v1, MPI_Fint *ierr ){
    *ierr = MPI_Grequest_complete( *v1 );
}
