# $Id: Makefile,v 1.1.1.1 2003/02/05 16:46:08 robl Exp $
#
#	Makefile for netcdf man
#

include ../macros.make

PACKING_LIST	= Makefile	\
		  netcdf.m4

all:

test:

install:

uninstall:

include ../rules.make
